/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package hotel;

import com.opencsv.CSVReader;
import com.opencsv.CSVReaderBuilder;
import com.opencsv.exceptions.CsvException;
import com.opencsv.exceptions.CsvValidationException;
import java.awt.Color;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class manageroom extends javax.swing.JFrame {



    /** Creates new form manageroom */
    public manageroom() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        roomno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        type = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        price = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table1 = new javax.swing.JTable();
        loaddata = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        reserved = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Manage Rooms");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 270, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Room No:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 100, 20));
        jPanel1.add(roomno, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 160, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Type:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, 30));

        type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double", "Triple", "Family", "Suite" }));
        type.setSelectedIndex(-1);
        type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeActionPerformed(evt);
            }
        });
        jPanel1.add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 160, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Price:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        price.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "800", "1200", "1500", "2500", "4000" }));
        price.setToolTipText("");
        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });
        jPanel1.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 160, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Reserved Status:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        add.setBackground(new java.awt.Color(255, 204, 0));
        add.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        add.setForeground(new java.awt.Color(0, 0, 51));
        add.setText("Add");
        add.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addMouseExited(evt);
            }
        });
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 80, 30));

        reset.setBackground(new java.awt.Color(255, 204, 0));
        reset.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        reset.setForeground(new java.awt.Color(0, 0, 51));
        reset.setText("Reset");
        reset.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                resetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                resetMouseExited(evt);
            }
        });
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel1.add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 130, 30));

        back.setBackground(new java.awt.Color(255, 204, 0));
        back.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        back.setForeground(new java.awt.Color(0, 0, 51));
        back.setText("Back");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
        });
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 130, 30));

        Table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room No", "Type", "Price", "Reserved Status"
            }
        ));
        jScrollPane1.setViewportView(Table1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 420, 390));

        loaddata.setBackground(new java.awt.Color(255, 153, 0));
        loaddata.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        loaddata.setForeground(new java.awt.Color(0, 0, 51));
        loaddata.setText("Load Data");
        loaddata.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        loaddata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loaddataMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loaddataMouseExited(evt);
            }
        });
        loaddata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loaddataActionPerformed(evt);
            }
        });
        jPanel1.add(loaddata, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, 420, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("X");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 10, -1, -1));

        reserved.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        reserved.setSelectedIndex(-1);
        jPanel1.add(reserved, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 150, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 480));

        setSize(new java.awt.Dimension(938, 471));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
       
      // TODO add your handling code here:
      roomno.setText("");
                        type.setSelectedIndex(-1);
                         price.setSelectedIndex(-1);
                          reserved.setSelectedIndex(-1);
    }//GEN-LAST:event_resetActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        new MainForm().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseEntered
        add.setForeground(Color.black);
        add.setBackground(Color.white); 
       add.setBorderPainted(false);
        Border border = BorderFactory.createMatteBorder(1,1,1,1,Color.blue);
        add.setBorder(border);// TODO add your handling code here:
    }//GEN-LAST:event_addMouseEntered

    private void addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseExited
         add.setForeground(Color.black);
         add.setBackground(new Color(255,204,0));// TODO add your handling code here:
    }//GEN-LAST:event_addMouseExited

    private void resetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetMouseEntered
         reset.setForeground(Color.black);
        reset.setBackground(Color.white); 
       reset.setBorderPainted(false);
        Border border = BorderFactory.createMatteBorder(1,1,1,1,Color.blue);
        reset.setBorder(border);// TODO add your handling code here:
    }//GEN-LAST:event_resetMouseEntered

    private void resetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetMouseExited
         reset.setForeground(Color.black);
         reset.setBackground(new Color(255,204,0));// TODO add your handling code here:
    }//GEN-LAST:event_resetMouseExited

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
         back.setForeground(Color.black);
        back.setBackground(Color.white); 
       back.setBorderPainted(false);
        Border border = BorderFactory.createMatteBorder(1,1,1,1,Color.blue);
        back.setBorder(border);// TODO add your handling code here:
    }//GEN-LAST:event_backMouseEntered

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
         back.setForeground(Color.black);
         back.setBackground(new Color(255,204,0));// TODO add your handling code here:
    }//GEN-LAST:event_backMouseExited

    private void loaddataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loaddataMouseEntered
         loaddata.setForeground(Color.black);
         loaddata.setBackground(Color.white); 
        loaddata.setBorderPainted(false);
        Border border = BorderFactory.createMatteBorder(1,1,1,1,Color.blue);
         loaddata.setBorder(border);// TODO add your handling code here:
    }//GEN-LAST:event_loaddataMouseEntered

    private void loaddataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loaddataMouseExited
          loaddata.setForeground(Color.black);
          loaddata.setBackground(new Color(255,153,0));// TODO add your handling code here:
    }//GEN-LAST:event_loaddataMouseExited

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
         Border signup_border = BorderFactory.createMatteBorder(1,1,1,1,Color.white);
        jLabel6.setBorder(signup_border);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
         Border signup_border = BorderFactory.createMatteBorder(0,0,0,0,Color.white);
       jLabel6.setBorder(signup_border);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseExited

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        System.exit(0);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeActionPerformed

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceActionPerformed

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
        // TODO add your handling code here:
        String room_no=roomno.getText();
        String room_type= type.getSelectedItem().toString();
        String room_price=price.getSelectedItem().toString();
        String reserved_status=reserved.getSelectedItem().toString();
        int p;
        p = new ForRooms().addRoom(room_no,room_type, room_price,reserved_status);
                        
         if(p==0){
                        
            JOptionPane.showMessageDialog(this,"This room is taken, Assign another room", "Error",JOptionPane.ERROR_MESSAGE);
          }
          
           else{
              

            JOptionPane.showMessageDialog(this,"New Room Added successfully", "Add Room",JOptionPane.INFORMATION_MESSAGE);

                                        
            }

        
    }//GEN-LAST:event_addMouseClicked

    private void loaddataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loaddataActionPerformed
        // TODO add your handling code here:
        
      /*   FileReader filereader = null;
        try {
          filereader = new FileReader("Rooms.csv");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(manageroom.class.getName()).log(Level.SEVERE, null, ex);
        }
          
              CSVReader reader = new CSVReaderBuilder(filereader).withSkipLines(1).build();       
             // String[] arr1;
              Object[] row;
              
            try{
                while((row=reader.readNext())!=null){
                   // for(int i=0;i< arr1.length;i++){
                        row=new Object[7];
                      //  s[k][i]=arr1[i];
                        DefaultTableModel tablemodel=(DefaultTableModel)Table1.getModel() ;
                      // DefaultTableModel model = new DefaultTableModel();
                       //jTablel1 table;
                       
                        row[0]=roomno.getText();
                        row[1]=type.getSelectedItem().toString();
                        row[2]=price.getSelectedItem().toString();
                        row[3]=reserved.getSelectedItem().toString();
                        
                        
                        tablemodel.addRow(row);
                        
                        
                        roomno.setText("");
                        type.setSelectedItem("");
                        price.setSelectedItem("");
                    

                        
                        break;
                   // }
                    
                }  
            }
            catch (IOException ex) {
                Logger.getLogger(manageroom.class.getName()).log(Level.SEVERE, null, ex);
            } catch (CsvValidationException ex) {
                Logger.getLogger(manageroom.class.getName()).log(Level.SEVERE, null, ex);
            }
        catch(CsvException e){
             e.printStackTrace();

        }  */
             FileReader filereader = null;
        try {
          filereader = new FileReader("Rooms.csv");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(manageroom.class.getName()).log(Level.SEVERE, null, ex);
        }
          
              CSVReader reader = new CSVReaderBuilder(filereader).withSkipLines(1).build();       
             List<String[]> Users = null;
        try {
            Users = reader.readAll();
        } catch (IOException ex) {
            Logger.getLogger(manageroom.class.getName()).log(Level.SEVERE, null, ex);
        } catch (CsvException ex) {
            Logger.getLogger(manageroom.class.getName()).log(Level.SEVERE, null, ex);
        }
           for(String[] user:Users){
               // if(user[0].toLowerCase().equals(username.toLowerCase().trim()) && user[5].equals(password.trim())){
                 //   flag=1;                  
                   // break;
               // }
               Vector<String>vs = new Vector<String>();
               
               for(String str:user){
               
                vs.add(str);   
               
               }
               DefaultTableModel tablemodel = (DefaultTableModel)Table1.getModel();
               tablemodel.addRow(vs);
            }
              
            
              
           
        
    }//GEN-LAST:event_loaddataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manageroom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manageroom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manageroom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manageroom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manageroom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table1;
    private javax.swing.JButton add;
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton loaddata;
    private javax.swing.JComboBox<String> price;
    private javax.swing.JComboBox<String> reserved;
    private javax.swing.JButton reset;
    private javax.swing.JTextField roomno;
    private javax.swing.JComboBox<String> type;
    // End of variables declaration//GEN-END:variables

}
