/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel;

import com.opencsv.CSVParser;
import com.opencsv.CSVReader;
import com.opencsv.CSVReaderBuilder;
import com.opencsv.exceptions.CsvException;
import com.opencsv.exceptions.CsvValidationException;
import static com.sun.xml.internal.fastinfoset.alphabet.BuiltInRestrictedAlphabets.table;
import java.awt.Color;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author USER
 */
public class manageclient extends javax.swing.JFrame {

    /**
     * Creates new form manageclient
     */
    //ClientsRead client=new ClientsRead();
    //private Object client_id;
    //private Object first_name;
    public manageclient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        client_id = new javax.swing.JTextField();
        first_name = new javax.swing.JTextField();
        last_name = new javax.swing.JTextField();
        phone_no = new javax.swing.JTextField();
        client_email = new javax.swing.JTextField();
        room_no = new javax.swing.JTextField();
        country = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        loaddata = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        gender = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1110, 538));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Manage Clients");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 52, 270, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("First Name:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Last Name:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Phone No:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Email:");
        jLabel5.setToolTipText("");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Gender:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Country:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Client ID:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Room No:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        client_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client_idActionPerformed(evt);
            }
        });
        jPanel1.add(client_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 140, 30));

        first_name.setToolTipText("");
        jPanel1.add(first_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 140, 30));
        jPanel1.add(last_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 140, 30));
        jPanel1.add(phone_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 140, 30));
        jPanel1.add(client_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 140, 30));
        jPanel1.add(room_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 140, 30));
        jPanel1.add(country, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 140, 30));

        add.setBackground(new java.awt.Color(255, 204, 0));
        add.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        add.setForeground(new java.awt.Color(0, 0, 51));
        add.setText("Add");
        add.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addMouseExited(evt);
            }
        });
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 80, 30));

        reset.setBackground(new java.awt.Color(255, 204, 0));
        reset.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        reset.setForeground(new java.awt.Color(0, 0, 51));
        reset.setText("Reset");
        reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                resetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                resetMouseExited(evt);
            }
        });
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel1.add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 130, 30));

        back.setBackground(new java.awt.Color(255, 204, 0));
        back.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        back.setForeground(new java.awt.Color(0, 0, 51));
        back.setText("Back");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
        });
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, 130, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Client ID", "First Name", "Last Name", "Phone No", "Email", "Gender", "Country", "Room No"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 580, 470));

        loaddata.setBackground(new java.awt.Color(255, 153, 0));
        loaddata.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        loaddata.setForeground(new java.awt.Color(0, 0, 51));
        loaddata.setText("Load Data");
        loaddata.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        loaddata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loaddataMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loaddataMouseExited(evt);
            }
        });
        loaddata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loaddataActionPerformed(evt);
            }
        });
        jPanel1.add(loaddata, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 480, 580, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("X");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel11MouseExited(evt);
            }
        });
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 10, -1, -1));

        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        gender.setSelectedIndex(-1);
        jPanel1.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 140, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 540));

        setSize(new java.awt.Dimension(1113, 538));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseEntered
         add.setForeground(Color.black);
        add.setBackground(Color.white); 
       add.setBorderPainted(false);
        Border border = BorderFactory.createMatteBorder(1,1,1,1,Color.blue);
        add.setBorder(border);// TODO add your handling code here:
    }//GEN-LAST:event_addMouseEntered

    private void addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseExited
         add.setForeground(Color.black);
         add.setBackground(new Color(255,204,0));// TODO add your handling code here:
    }//GEN-LAST:event_addMouseExited

    private void resetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetMouseEntered
        reset.setForeground(Color.black);
        reset.setBackground(Color.white); 
       reset.setBorderPainted(false);
        Border border = BorderFactory.createMatteBorder(1,1,1,1,Color.blue);
        reset.setBorder(border);// TODO add your handling code here:
    }//GEN-LAST:event_resetMouseEntered

    private void resetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetMouseExited
         reset.setForeground(Color.black);
         reset.setBackground(new Color(255,204,0));// TODO add your handling code here:
    }//GEN-LAST:event_resetMouseExited

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
         back.setForeground(Color.black);
        back.setBackground(Color.white); 
       back.setBorderPainted(false);
        Border border = BorderFactory.createMatteBorder(1,1,1,1,Color.blue);
        back.setBorder(border);// TODO add your handling code here:
    }//GEN-LAST:event_backMouseEntered

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
         back.setForeground(Color.black);
         back.setBackground(new Color(255,204,0));// TODO add your handling code here:
    }//GEN-LAST:event_backMouseExited

    private void loaddataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loaddataMouseEntered
         loaddata.setForeground(Color.black);
         loaddata.setBackground(Color.white); 
        loaddata.setBorderPainted(false);
        Border border = BorderFactory.createMatteBorder(1,1,1,1,Color.blue);
         loaddata.setBorder(border);// TODO add your handling code here:
    }//GEN-LAST:event_loaddataMouseEntered

    private void loaddataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loaddataMouseExited
        loaddata.setForeground(Color.black);
          loaddata.setBackground(new Color(255,153,0));// TODO add your handling code here:
    }//GEN-LAST:event_loaddataMouseExited

    private void jLabel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseEntered
         Border signup_border = BorderFactory.createMatteBorder(1,1,1,1,Color.white);
        jLabel11.setBorder(signup_border);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseEntered

    private void jLabel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseExited
         Border signup_border = BorderFactory.createMatteBorder(0,0,0,0,Color.white);
       jLabel11.setBorder(signup_border);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseExited

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
      System.exit(0);  // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseClicked

    private void client_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_client_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_client_idActionPerformed

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
        // TODO add your handling code here:
        String ClientId = client_id.getText();
        String firstname= first_name.getText();
        String lastname = last_name.getText();
        String phoneno = phone_no.getText();
        String Gender = gender.getSelectedItem().toString();
        String clientmail = client_email.getText();
        String Country = country.getText();
        String roomno = room_no.getText();

        
        int p= new ForClients().addClient(ClientId, firstname, lastname,phoneno,Gender,clientmail,Country,roomno);
                        
         if(p==0){
                        
            JOptionPane.showMessageDialog(this,"Username is taken, Try another one", "Error",JOptionPane.ERROR_MESSAGE);
          }
          else if(p==1){
                            
            JOptionPane.showMessageDialog(this,"Email is already being used, Try another one", "Error",JOptionPane.ERROR_MESSAGE);

                        
           }
           else{
              
              //String data[]={client_id.getText(),first_name.getText(), last_name.getText(), phone_no.getText(),client_email.getText(), country.getText(), room_no.getText()};
               //DefaultTableModel tmodel=(DefaultTableModel)jTable1.getModel() ;

            JOptionPane.showMessageDialog(this,"New Client Added successfully", "Add Client",JOptionPane.INFORMATION_MESSAGE);
             
            


                // new manageroom().setVisible(true);
                
                        
            }




    }//GEN-LAST:event_addMouseClicked

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        
        
        
        
//        if("".equals(client_id.getText().trim())||
//                "".equals(first_name.getText().trim())||
//                "".equals(last_name.getText().trim())||
//            "".equals(phone_no.getText().trim())||
//            "".equals(client_email.getText().trim())||
//            "".equals(country.getText().trim()) ||
//                "".equals(room_no.getText().trim())
//             )
//        {
//            JOptionPane.showMessageDialog(this,"Please enter all data", "Error",JOptionPane.ERROR_MESSAGE);
//  
//        }
//        else{
//        String data[]={client_id.getText(),first_name.getText(), last_name.getText(), phone_no.getText(),client_email.getText(), country.getText(), room_no.getText()};
//               DefaultTableModel tmodel=(DefaultTableModel)jTable1.getModel() ;
//
//           // JOptionPane.showMessageDialog(this,"Data added successfully", "Error",JOptionPane.ERROR_MESSAGE);
//             
//            client_id.setText("");
//            first_name.setText("");
//            last_name.setText("");
//            phone_no.setText("");
//            client_email.setText("");
//            country.setText("");
//            room_no.setText("");
        //}
    }//GEN-LAST:event_addActionPerformed

    private void loaddataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loaddataActionPerformed
        // TODO add your handling code here:
       // String[][] s = new String[50][50];
        //int k=0;
        
        
       /* 
        File csv_file=new File("Clients.csv");
        DefaultTableModel csv_data=new DefaultTableModel();
        
        try{
            int start=0;
          InputStreamReader reader = new InputStreamReader(new FileInputStream(csv_file));
          CSVParser csvParser = CSVFormat.Default.parse(reader);
          for(CSVRecord csvRecord : csvParser)
          {
              if (start==0){
              
               start=0;
               csv_data.addColumn(csvRecord.get(0));
               csv_data.addColumn(csvRecord.get(1));
               csv_data.addColumn(csvRecord.get(2));
               csv_data.addColumn(csvRecord.get(3));
               csv_data.addColumn(csvRecord.get(4));
               csv_data.addColumn(csvRecord.get(5));
               csv_data.addColumn(csvRecord.get(6));
               
              
              }
                    
              Vector row =new Vector();  
              
              row.add(csvRecord.get(0));
              row.add(csvRecord.get(1));
              row.add(csvRecord.get(2));
              row.add(csvRecord.get(3));
              row.add(csvRecord.get(4));
              row.add(csvRecord.get(5));
              row.add(csvRecord.get(6));
              
              csv_data.addRow(row);
          
          
          }
        
        }  */
             
        
        
       FileReader filereader = null;
        try {
          filereader = new FileReader("Clients.csv");
        }
        catch (FileNotFoundException ex) {
            Logger.getLogger(manageclient.class.getName()).log(Level.SEVERE, null, ex);
        }
          
              CSVReader reader = new CSVReaderBuilder(filereader).withSkipLines(1).build();       
             List<String[]> Users = null;
        try {
            Users = reader.readAll();
        } catch (IOException ex) {
            Logger.getLogger(manageclient.class.getName()).log(Level.SEVERE, null, ex);
        } catch (CsvException ex) {
            Logger.getLogger(manageclient.class.getName()).log(Level.SEVERE, null, ex);
        }
           for(String[] user:Users){
               // if(user[0].toLowerCase().equals(username.toLowerCase().trim()) && user[5].equals(password.trim())){
                 //   flag=1;                  
                   // break;
               // }
               Vector<String>vs = new Vector<String>();
               
               for(String str:user){
               
                vs.add(str);   
               
               }
               DefaultTableModel tablemodel = (DefaultTableModel)jTable1.getModel();
               tablemodel.addRow(vs);
            }
              
          
          /*  Object[] row;
              
            try{
                while((row=reader.readNext())!=null){
                   // for(int i=0;i< arr1.length;i++){
                        row=new Object[8];
                      //  s[k][i]=arr1[i];
                        DefaultTableModel tablemodel=(DefaultTableModel)jTable1.getModel() ;
                      // DefaultTableModel model = new DefaultTableModel();
                       //jTablel1 table;
                       
                        row[0]=client_id.getText();
                        row[1]=first_name.getText();
                        row[2]=last_name.getText();
                        row[3]=phone_no.getText();
                        row[4]=client_email.getText();
                        row[5]=gender.getSelectedItem().toString();
                        row[6]=country.getText();
                        row[7]=room_no.getText();
                        
                        tablemodel.addRow(row);
                        
                        System.out.println(row[0]);
                        System.out.println(row[1]);
                        System.out.println(row[2]);
                       

                        
                      //  break;
                   // }
                    
                }  
            }*/
         /*   catch (IOException ex) {
                Logger.getLogger(manageclient.class.getName()).log(Level.SEVERE, null, ex);
            } catch (CsvValidationException ex) {
                Logger.getLogger(manageclient.class.getName()).log(Level.SEVERE, null, ex);
            }
        catch(CsvException e){
             e.printStackTrace();  

        }
            //jTable1.setModel(new DefaultTableModel(null,new Object[]{"Client Id","First Name","Last Name","Phone No","Email","Gender","Country","Room No"}));
            */
            
            
    }//GEN-LAST:event_loaddataActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        client_id.setText("");
                        first_name.setText("");
                        last_name.setText("");
                        phone_no.setText("");
                        client_email.setText("");
                        gender.setSelectedIndex(-1);
                        country.setText("");
                        room_no.setText("");
                        
    }//GEN-LAST:event_resetActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        new MainForm().setVisible(true);  
    }//GEN-LAST:event_backActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manageclient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manageclient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manageclient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manageclient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manageclient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton back;
    private javax.swing.JTextField client_email;
    private javax.swing.JTextField client_id;
    private javax.swing.JTextField country;
    private javax.swing.JTextField first_name;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField last_name;
    private javax.swing.JButton loaddata;
    private javax.swing.JTextField phone_no;
    private javax.swing.JButton reset;
    private javax.swing.JTextField room_no;
    // End of variables declaration//GEN-END:variables
}
