/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel;

import com.opencsv.CSVReader;
import com.opencsv.CSVReaderBuilder;
import com.opencsv.exceptions.CsvException;
import com.opencsv.exceptions.CsvValidationException;
import com.toedter.calendar.JDateChooser;
import java.awt.Color;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class RoomReservation extends javax.swing.JFrame {

    /**
     * Creates new form RoomReservation
     */
    public RoomReservation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanel1 = new javax.swing.JPanel();
        label_manage = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        label_idd = new javax.swing.JLabel();
        ID = new javax.swing.JComboBox<>();
        label_clientid = new javax.swing.JLabel();
        ClientID = new javax.swing.JTextField();
        label_roomno = new javax.swing.JLabel();
        roomno = new javax.swing.JTextField();
        label_datein = new javax.swing.JLabel();
        label_dateout = new javax.swing.JLabel();
        dateOut = new com.toedter.calendar.JDateChooser();
        dateIn = new com.toedter.calendar.JDateChooser();
        add = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        loaddata = new javax.swing.JButton();
        label_cross = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        deposit = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpanel1.setBackground(new java.awt.Color(0, 51, 51));
        jpanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_manage.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        label_manage.setForeground(new java.awt.Color(255, 255, 255));
        label_manage.setText("Manage Reservations");
        jpanel1.add(label_manage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
        jpanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 52, 380, 10));

        label_idd.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        label_idd.setForeground(new java.awt.Color(255, 255, 255));
        label_idd.setText("ID:");
        jpanel1.add(label_idd, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        ID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NID", "Passport" }));
        ID.setSelectedIndex(-1);
        ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDActionPerformed(evt);
            }
        });
        jpanel1.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 160, 30));

        label_clientid.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        label_clientid.setForeground(new java.awt.Color(255, 255, 255));
        label_clientid.setText("Client ID:");
        jpanel1.add(label_clientid, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        ClientID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientIDActionPerformed(evt);
            }
        });
        jpanel1.add(ClientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 160, 30));

        label_roomno.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        label_roomno.setForeground(new java.awt.Color(255, 255, 255));
        label_roomno.setText("Room No:");
        jpanel1.add(label_roomno, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));
        jpanel1.add(roomno, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 160, 30));

        label_datein.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        label_datein.setForeground(new java.awt.Color(255, 255, 255));
        label_datein.setText("Date In:");
        jpanel1.add(label_datein, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        label_dateout.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        label_dateout.setForeground(new java.awt.Color(255, 255, 255));
        label_dateout.setText("Date Out:");
        jpanel1.add(label_dateout, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));
        jpanel1.add(dateOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 160, 30));
        jpanel1.add(dateIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 160, 30));

        add.setBackground(new java.awt.Color(255, 204, 0));
        add.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        add.setForeground(new java.awt.Color(0, 0, 51));
        add.setText("Add");
        add.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addMouseExited(evt);
            }
        });
        jpanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, 90, 30));

        reset.setBackground(new java.awt.Color(255, 204, 0));
        reset.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        reset.setForeground(new java.awt.Color(0, 0, 51));
        reset.setText("Reset");
        reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                resetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                resetMouseExited(evt);
            }
        });
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jpanel1.add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 140, 30));

        back.setBackground(new java.awt.Color(255, 204, 0));
        back.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        back.setText("Back");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
        });
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jpanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, 150, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Client ID", "Room No", "Date In", "Date Out", "Deposit"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jpanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 17, 450, 440));

        loaddata.setBackground(new java.awt.Color(255, 153, 0));
        loaddata.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        loaddata.setForeground(new java.awt.Color(0, 0, 51));
        loaddata.setText("Load Data");
        loaddata.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        loaddata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loaddataMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loaddataMouseExited(evt);
            }
        });
        loaddata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loaddataActionPerformed(evt);
            }
        });
        jpanel1.add(loaddata, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 460, 450, 30));

        label_cross.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label_cross.setForeground(new java.awt.Color(255, 255, 255));
        label_cross.setText("X");
        label_cross.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_crossMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_crossMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_crossMouseExited(evt);
            }
        });
        jpanel1.add(label_cross, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Deposit:");
        jpanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));

        deposit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "800", "1200", "1500", "2500", "4000" }));
        deposit.setSelectedIndex(-1);
        jpanel1.add(deposit, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 160, 30));

        getContentPane().add(jpanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 520));

        setSize(new java.awt.Dimension(1061, 517));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseEntered
         add.setForeground(Color.black);
        add.setBackground(Color.white); 
       add.setBorderPainted(false);
        Border border = BorderFactory.createMatteBorder(1,1,1,1,Color.blue);
        add.setBorder(border);// TODO add your handling code here:
    }//GEN-LAST:event_addMouseEntered

    private void addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseExited
        add.setForeground(Color.black);
         add.setBackground(new Color(255,204,0)); // TODO add your handling code here:
    }//GEN-LAST:event_addMouseExited

    private void resetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetMouseEntered
        reset.setForeground(Color.black);
        reset.setBackground(Color.white); 
       reset.setBorderPainted(false);
        Border border = BorderFactory.createMatteBorder(1,1,1,1,Color.blue);
        reset.setBorder(border);// TODO add your handling code here:
    }//GEN-LAST:event_resetMouseEntered

    private void resetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetMouseExited
        reset.setForeground(Color.black);
         reset.setBackground(new Color(255,204,0));// TODO add your handling code here:
    }//GEN-LAST:event_resetMouseExited

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
         back.setForeground(Color.black);
        back.setBackground(Color.white); 
       back.setBorderPainted(false);
        Border border = BorderFactory.createMatteBorder(1,1,1,1,Color.blue);
        back.setBorder(border);// TODO add your handling code here:
    }//GEN-LAST:event_backMouseEntered

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
         back.setForeground(Color.black);
         back.setBackground(new Color(255,204,0));// TODO add your handling code here:
    }//GEN-LAST:event_backMouseExited

    private void loaddataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loaddataMouseEntered
        loaddata.setForeground(Color.black);
         loaddata.setBackground(Color.white); 
        loaddata.setBorderPainted(false);
        Border border = BorderFactory.createMatteBorder(1,1,1,1,Color.blue);
         loaddata.setBorder(border);// TODO add your handling code here:
    }//GEN-LAST:event_loaddataMouseEntered

    private void loaddataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loaddataMouseExited
        loaddata.setForeground(Color.black);
          loaddata.setBackground(new Color(255,153,0));// TODO add your handling code here:
    }//GEN-LAST:event_loaddataMouseExited

    private void IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDActionPerformed

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
        // TODO add your handling code here:
        String id = ID.getSelectedItem().toString();
        String client_id = ClientID.getText();
        String room_no=roomno.getText();
        
        SimpleDateFormat dateformat = new SimpleDateFormat("dd/mm/yyyy");
        String date_in = dateformat.format(dateIn.getDate());
        String date_out = dateformat.format(dateOut.getDate());
        String Deposit=deposit.getSelectedItem().toString();
        
        
       // String date_in  = (dateIn.getDateEditor().getUiComponent()).toString();
       // String date_out =(dateOut.getDateEditor().getUiComponent()).toString();


        
        int p;
        p = new ForReservation().addReservation(id, client_id, room_no, date_in, date_out, Deposit);
                        
         
         
         if(p==0){
                        
            JOptionPane.showMessageDialog(this,"This Client ID is taken , Please try another onr", "Error",JOptionPane.ERROR_MESSAGE);
          }
         
         else if(p==1){
                        
            JOptionPane.showMessageDialog(this,"This room is taken, Assign another room", "Error",JOptionPane.ERROR_MESSAGE);
          }
         
          
           else{
              

            JOptionPane.showMessageDialog(this,"New Reservation Added successfully", "Add Reservation",JOptionPane.INFORMATION_MESSAGE);

                                        
            }
        
        
    }//GEN-LAST:event_addMouseClicked

    private void ClientIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClientIDActionPerformed

    private void label_crossMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_crossMouseExited
        Border signup_border = BorderFactory.createMatteBorder(0,0,0,0,Color.white);
        label_cross.setBorder(signup_border);// TODO add your handling code here:
    }//GEN-LAST:event_label_crossMouseExited

    private void label_crossMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_crossMouseEntered
        Border signup_border = BorderFactory.createMatteBorder(1,1,1,1,Color.white);
        label_cross.setBorder(signup_border);// TODO add your handling code here:
    }//GEN-LAST:event_label_crossMouseEntered

    private void label_crossMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_crossMouseClicked
        System.exit(0);// TODO add your handling code here:
    }//GEN-LAST:event_label_crossMouseClicked

    private void loaddataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loaddataActionPerformed
        // TODO add your handling code here:
        
     /*    FileReader filereader = null;
        try {
          filereader = new FileReader("Reservation.csv");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(RoomReservation.class.getName()).log(Level.SEVERE, null, ex);
        }
          
              CSVReader reader = new CSVReaderBuilder(filereader).withSkipLines(1).build();        
              String[] arr1;
          
            Object[] row;
            SimpleDateFormat dateformat = new SimpleDateFormat("dd/mm/yyyy");   
            try{
                while((row=reader.readNext())!=null){
                   // for(int i=0;i< arr1.length;i++){
                        row=new Object[7];
                      //  s[k][i]=arr1[i];
                        DefaultTableModel tablemodel=(DefaultTableModel)jTable1.getModel() ;
                      // DefaultTableModel model = new DefaultTableModel();
                       //jTablel1 table;
                       
                        row[0]=ID.getSelectedItem().toString();
                        row[1]=ClientID.getText();
                        row[2]=roomno.getText();
                    //    SimpleDateFormat dateformat = new SimpleDateFormat("dd/mm/yyyy");
                        
                        
                        row[3]=dateformat.format(dateIn.getDate());
                        row[4]=dateformat.format(dateOut.getDate());
                        row[5]=deposit.getSelectedItem().toString();
                        
                        
                        tablemodel.addRow(row);
                        
                       
                       

                        
                        break;
                   // }
                    
                }  
            }
            catch (IOException ex) {
                Logger.getLogger(RoomReservation.class.getName()).log(Level.SEVERE, null, ex);
            } catch (CsvValidationException ex) {
                Logger.getLogger(RoomReservation.class.getName()).log(Level.SEVERE, null, ex);
            }
        catch(CsvException e){
             e.printStackTrace();

        }   
            */
       
              FileReader filereader = null;
        try {
          filereader = new FileReader("Reservation.csv");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(RoomReservation.class.getName()).log(Level.SEVERE, null, ex);
        }
          
              CSVReader reader = new CSVReaderBuilder(filereader).withSkipLines(1).build();       
             List<String[]> Users = null;
        try {
            Users = reader.readAll();
        } catch (IOException | CsvException ex) {
            Logger.getLogger(RoomReservation.class.getName()).log(Level.SEVERE, null, ex);
        }
           for(String[] user:Users){
               // if(user[0].toLowerCase().equals(username.toLowerCase().trim()) && user[5].equals(password.trim())){
                 //   flag=1;                  
                   // break;
               // }
               Vector<String>vs = new Vector<String>();
               
               for(String str:user){
               
                vs.add(str);   
               
               }
               DefaultTableModel tablemodel = (DefaultTableModel)jTable1.getModel();
               tablemodel.addRow(vs);
            }
              
        
        
    }//GEN-LAST:event_loaddataActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
         new MainForm().setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
         //ID.setSelectedIndex(-1);
         ClientID.setText("");
         roomno.setText("");
       //  dateIn.setDate(null);
         // dateOut.setDate(null);
          //deposit.setSelectedIndex(0);
    }//GEN-LAST:event_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoomReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoomReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoomReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoomReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RoomReservation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ClientID;
    private javax.swing.JComboBox<String> ID;
    private javax.swing.JButton add;
    private javax.swing.JButton back;
    private com.toedter.calendar.JDateChooser dateIn;
    private com.toedter.calendar.JDateChooser dateOut;
    private javax.swing.JComboBox<String> deposit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel jpanel1;
    private javax.swing.JLabel label_clientid;
    private javax.swing.JLabel label_cross;
    private javax.swing.JLabel label_datein;
    private javax.swing.JLabel label_dateout;
    private javax.swing.JLabel label_idd;
    private javax.swing.JLabel label_manage;
    private javax.swing.JLabel label_roomno;
    private javax.swing.JButton loaddata;
    private javax.swing.JButton reset;
    private javax.swing.JTextField roomno;
    // End of variables declaration//GEN-END:variables
}
